export const voiceSettingsStorageKey = "aeye-voice-settings";

export const defaultVoiceSettings = {
  sttLanguage: "en-US",
  ttsLanguage: "en-US",
  ttsVoiceName: null,
};

export const availableResponseLanguages = {
  "ar-SA": "Saudi Arabia Arabic (ar-SA)",
  "bg-BG": "Bulgarian (bg-BG)",
  "bn-IN": "Bengali (bn-IN)",
  "cs-CZ": "Czech (cs-CZ)",
  "da-DK": "Danish (da-DK)",
  "de-DE": "German (de-DE)",
  "el-GR": "Greek (el-GR)",
  "en-GB": "UK English (en-GB)",
  "en-US": "US English (en-US)",
  "es-ES": "Spain Spanish (es-ES)",
  "es-US": "US Spanish (es-US)",
  "fa-IR": "Persian (fa-IR)",
  "fi-FI": "Finnish (fi-FI)",
  "fr-FR": "French (fr-FR)",
  "he-IL": "Hebrew (he-IL)",
  "hi-IN": "Hindi (hi-IN)",
  "hu-HU": "Hungarian (hu-HU)",
  "id-ID": "Indonesian (id-ID)",
  "it-IT": "Italian (it-IT)",
  "ja-JP": "Japanese (ja-JP)",
  "ko-KR": "Korean (ko-KR)",
  "ms-MY": "Malay (ms-MY)",
  "nb-NO": "Norwegian (nb-NO)",
  "nl-NL": "Dutch (nl-NL)",
  "pl-PL": "Polish (pl-PL)",
  "pt-BR": "Brazil Portuguese (pt-BR)",
  "pt-PT": "Portugal Portuguese (pt-PT)",
  "ro-RO": "Romanian (ro-RO)",
  "ru-RU": "Russian (ru-RU)",
  "sv-SE": "Swedish (sv-SE)",
  "th-TH": "Thai (th-TH)",
  "tr-TR": "Turkish (tr-TR)",
  "uk-UA": "Ukrainian (uk-UA)",
  "ur-PK": "Urdu (ur-PK)",
  "vi-VN": "Vietnamese (vi-VN)",
  "zh-CN": "简体中文(中国) (zh-CN)",
  "zh-HK": "繁體中文(粵語) (zh-HK)",
  "zh-TW": "繁體中文(台灣) (zh-TW)",
};

export const availableLanguages = {
  af: "Afrikaans (af)",
  "ar-AE": "UAE Arabic (ar-AE)",
  "ar-BH": "Bahrain Arabic (ar-BH)",
  "ar-DZ": "Algeria Arabic (ar-DZ)",
  "ar-EG": "Egypt Arabic (ar-EG)",
  "ar-IQ": "Iraq Arabic (ar-IQ)",
  "ar-JO": "Jordan Arabic (ar-JO)",
  "ar-KW": "Kuwait Arabic (ar-KW)",
  "ar-LB": "Lebanon Arabic (ar-LB)",
  "ar-LY": "Libya Arabic (ar-LY)",
  "ar-MA": "Morocco Arabic (ar-MA)",
  "ar-OM": "Oman Arabic (ar-OM)",
  "ar-QA": "Qatar Arabic (ar-QA)",
  "ar-SA": "Saudi Arabia Arabic (ar-SA)",
  "ar-TN": "Tunisia Arabic (ar-TN)",
  "ar-YE": "Yemen Arabic (ar-YE)",
  bg: "Bulgarian (bg)",
  ca: "Catalan (ca)",
  cs: "Czech (cs)",
  "de-DE": "German (de-DE)",
  "en-AU": "Australia English (en-AU)",
  "en-CA": "Canada English (en-CA)",
  "en-GB": "UK English (en-GB)",
  "en-IN": "India English (en-IN)",
  "en-NZ": "New Zealand English (en-NZ)",
  "en-US": "US English (en-US)",
  "en-ZA": "South Africa English (en-ZA)",
  "es-AR": "Argentina Spanish (es-AR)",
  "es-BO": "Bolivia Spanish (es-BO)",
  "es-CL": "Chile Spanish (es-CL)",
  "es-CO": "Colombia Spanish (es-CO)",
  "es-CR": "Costa Rica Spanish (es-CR)",
  "es-DO": "Dominican Republic Spanish (es-DO)",
  "es-EC": "Ecuador Spanish (es-EC)",
  "es-ES": "Spain Spanish (es-ES)",
  "es-SV": "El Salvador Spanish (es-SV)",
  "es-US": "US Spanish (es-US)",
  "es-GT": "Guatemala Spanish (es-GT)",
  "es-HN": "Honduras Spanish (es-HN)",
  "es-MX": "Mexico Spanish (es-MX)",
  "es-NI": "Nicaragua Spanish (es-NI)",
  "es-PA": "Panama Spanish (es-PA)",
  "es-PY": "Paraguay Spanish (es-PY)",
  "es-PE": "Peru Spanish (es-PE)",
  "es-PR": "Puerto Rico Spanish (es-PR)",
  "es-UY": "Uruguay Spanish (es-UY)",
  "es-VE": "Venezuela Spanish (es-VE)",
  eu: "Basque (eu)",
  fi: "Finnish (fi)",
  "fr-FR": "French (fr-FR)",
  gl: "Galician (gl)",
  he: "Hebrew (he)",
  hu: "Hungarian (hu)",
  id: "Indonesian (id)",
  is: "Icelandic (is)",
  "it-IT": "Italian (it-IT)",
  ja: "Japanese (ja)",
  ko: "Korean (ko)",
  la: "Latin (la)",
  "ms-MY": "Malay (ms-MY)",
  "nl-NL": "Dutch (nl-NL)",
  "no-NO": "Norwegian (no-NO)",
  pl: "Polish (pl)",
  "pt-BR": "Brazil Portuguese (pt-BR)",
  "pt-PT": "Portugal Portuguese (pt-PT)",
  "ro-RO": "Romanian (ro-RO)",
  ru: "Russian (ru)",
  sk: "Slovak (sk)",
  "sr-SP": "Serbian (sr-SP)",
  "sv-SE": "Swedish (sv-SE)",
  tr: "Turkish (tr)",
  "zh-CN": "简体中文(中国) (zh-CN)",
  "zh-TW": "繁體中文(台灣) (zh-TW)",
  "zh-yue": "繁體中文(粵語) (zh-yue)",
  zu: "Zulu (zu)",
};
