export const voiceSettingsStorageKey = 'aeye-voice-settings';

export const defaultVoiceSettings = {
    sttLanguage: 'en-US',
    ttsLanguage: 'en-US',
    ttsVoiceName: null
};

export const availableLanguages = {
    'af': 'Afrikaans',
    'ar-AE': 'Arabic (UAE)',
    'ar-BH': 'Arabic (Bahrain)',
    'ar-DZ': 'Arabic (Algeria)',
    'ar-EG': 'Arabic (Egypt)',
    'ar-IQ': 'Arabic (Iraq)',
    'ar-JO': 'Arabic (Jordan)',
    'ar-KW': 'Arabic (Kuwait)',
    'ar-LB': 'Arabic (Lebanon)',
    'ar-LY': 'Arabic (Lybia)',
    'ar-MA': 'Arabic (Morocco)',
    'ar-OM': 'Arabic (Oman)',
    'ar-QA': 'Arabic (Qatar)',
    'ar-SA': 'Arabic (Saudi Arabia)',
    'ar-TN': 'Arabic (Tunisia)',
    'ar-YE': 'Arabic (Yemen)',
    'bg': 'Bulgarian',
    'ca': 'Catalan',
    'cs': 'Czech',
    'de-DE': 'German (Deutschland)',
    'en-AU': 'English (Australia)',
    'en-CA': 'English (Canada)',
    'en-GB': 'English (UK)',
    'en-IN': 'English (India)',
    'en-NZ': 'English (New Zealand)',
    'en-US': 'English (US)',
    'en-ZA': 'English (South Africa)',
    'es-AR': 'Spanish (Argentina)',
    'es-BO': 'Spanish (Bolivia)',
    'es-CL': 'Spanish (Chile)',
    'es-CO': 'Spanish (Colombia)',
    'es-CR': 'Spanish (Costa Rica)',
    'es-DO': 'Spanish (Dominican Republic)',
    'es-EC': 'Spanish (Ecuador)',
    'es-ES': 'Spanish (España)',
    'es-SV': 'Spanish (El Salvador)',
    'es-US': 'Spanish (US)',
    'es-GT': 'Spanish (Guatemala)',
    'es-HN': 'Spanish (Honduras)',
    'es-MX': 'Spanish (Mexico)',
    'es-NI': 'Spanish (Nicaragua)',
    'es-PA': 'Spanish (Panama)',
    'es-PY': 'Spanish (Paraguay)',
    'es-PE': 'Spanish (Peru)',
    'es-PR': 'Spanish (Puerto Rico)',
    'es-UY': 'Spanish (Uruguay)',
    'es-VE': 'Spanish (Venezuela)',
    'eu': 'Basque',
    'fi': 'Finnish',
    'fr-FR': 'French (France)',
    'gl': 'Galician',
    'he': 'Hebrew',
    'hu': 'Hungarian',
    'id': 'Indonesian',
    'is': 'Icelandic',
    'it-IT': 'Italian (Italia)',
    'ja': 'Japanese',
    'ko': 'Korean',
    'la': 'Latin',
    'ms-MY': 'Malaysian',
    'nl-NL': 'Dutch (Nederland)',
    'no-NO': 'Norwegian (Norge)',
    'pl': 'Polish',
    'pt-BR': 'Portuguese (Brasil)',
    'pt-PT': 'Portuguese (Portugal)',
    'ro-RO': 'Romanian (România)',
    'ru': 'Russian',
    'sk': 'Slovak',
    'sr-SP': 'Serbian',
    'sv-SE': 'Swedish (Sverige)',
    'tr': 'Turkish',
    'zh-CN': 'Mandarin Chinese (China)',
    'zh-HK': 'Chinese (Simplified Hong Kong)',
    'zh-TW': 'Chinese (Traditional Taiwan)',
    'zh-yue': 'Yue Chinese (Hong Kong)',
    'zu': 'Zulu'
};