swagger: "2.0"
info:
  title: Gemini via API GW
  description: Proxies requests to a Cloud Function that calls Gemini/Vertex AI
  version: "1.0.0"
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  /gemini-proxy:
    post:
      summary: Proxy Gemini Request
      operationId: proxyGeminiRequest
      x-google-backend:
        address: https://<YOUR_CLOUD_FUNCTION_URL> # Replace with your Cloud Function URL
        protocol: h2
        deadline: 60
      security:
        - api_key: []
      responses:
        "200":
          description: Successful response from the backend
          schema:
            type: object
        default:
          description: Error response from the backend or gateway
          schema:
            type: object
securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header
